repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        files: 'mbrl'

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        files: 'mbrl'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        files: 'mbrl'
        additional_dependencies: [numpy, torch, tokenize-rt==3.2.0, types-PyYAML, types-termcolor]
        args: [--no-strict-optional, --ignore-missing-imports, --follow-imports=skip]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: 'mbrl'
      - id: isort
        files: 'tests'
        args: [ "--profile", "black" ]
